config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  get 'simple_pages/feedback'
  post 'simple_pages/feedback'
  post 'payments/create'
  get 'payments/create'
  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planet Globula</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
    <body>
      <header>
        <div class="container-fluid navigation">
          <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #a1dec0">
            <div class="navbar-header">
              <div class="navbar-brand">
                <%= link_to(image_tag("logo.jpg", width: "50", height: "51"), root_path) %>
              </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li role="presentation"><%= link_to root_path do %><span class="glyphicon glyphicon-home"></span><% end %></li>
                <li role="presentation"><%= link_to "About", simple_pages_about_path %></li>
                <li role="presentation"><%= link_to "Contact", simple_pages_contact_path %></li>
                <li role="presentation"><%= link_to products_path do %><span>Products</span><% end %></li>
                <li role="presentation"><%= link_to orders_path do %><span class="glyphicon glyphicon-shopping-cart"></span><% end %></li>
                <% if signed_in? && current_user.admin? %>
                  <li role="presentation"><%= link_to users_path do%><span class="glyphicon glyphicon-user"></span><% end %></li>
                <% elsif signed_in? && current_user %>
                  <li role="presentation"><%= link_to users_path do %><span class="glyphicon glyphicon-user"></span><% end %></li>
                <% end %>
              </ul>
              <div class="navbar-right">
                <%= form_tag("/products", method: "get") do %>
                <%= text_field_tag(:q, nil, id: 'q', value: params[:q], placeholder: "Find products...") %>
                <%= submit_tag("Search", class: 'btn btn-danger') %>
                <% end %>
              </div>
              <div class="navbar-right">
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, class: 'btn btn-danger', method: :delete) %>
                <% else %>
                  <%= link_to('Login', new_user_session_path, class: 'btn btn-danger') %>
                <% end %>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <div class="container">
          <%= yield %>
      </div>
      <%= render partial: "shared/feedback_form" %>
      <div class="container notifications">
        <% if notice %>
            <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
        <% end %>
      </div>
      <%= javascript_include_tag 'notifications.js' %>
      <div class="footer">
        <div class="container">
          <p class="text-muted"><span class="glyphicon glyphicon-grain"></span>Planet Globula 2018</p>
        </div>
      </div>
    </body>
  </html>